######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 3 15:57:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plugin.h
SOURCES += main.cpp
