#line 2 "query_lexer.C"

#line 4 "query_lexer.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[469] =
    {   0,
        0,    0,   59,   59,    0,    0,   66,   66,   71,   71,
       74,   74,    0,    0,    0,    0,   79,   76,   17,   17,
       76,   22,   76,   28,   20,   21,   27,   30,   24,   18,
       18,   18,   18,   18,   18,   18,   26,   25,   59,   59,
       76,   76,   55,   76,   57,   46,   38,   50,   41,   39,
       42,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   34,   54,   78,   76,   76,   60,   66,   66,   63,
       64,   76,   65,   62,   67,   72,   71,   71,   72,   76,
       72,   70,   69,   76,   74,   74,   76,   73,   75,   76,
       17,    0,   77,   19,    0,    0,    0,   19,    0,   32,

        0,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   59,   40,    0,   77,   58,    0,    0,    0,   58,
       52,   43,   44,    0,    0,    0,    0,    0,   45,   47,
        0,    0,    0,    0,   77,    0,    0,    0,   60,   66,
        0,   61,    0,   67,   72,    0,    0,    0,   71,   72,
       72,    0,    0,    0,    0,    0,    0,    0,    0,   72,
       68,   74,    0,    0,   75,    0,    0,    0,    0,    0,
        0,    0,   19,    0,    0,    0,    0,    0,    0,   18,
        0,   18,   18,   18,    0,   18,    0,   29,   18,   18,
       18,    0,    0,    0,    0,    0,    0,    0,   58,    0,

        0,    0,    0,    0,    0,   37,    0,    0,    0,    0,
        0,    0,    0,   60,    0,   67,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   75,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   77,    0,   19,
        0,    0,   18,   18,   18,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   18,   18,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   77,    0,   58,    0,
        0,   36,    0,    0,   35,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   18,   18,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   23,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   56,    0,   48,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,    0,    6,    0,    0,
        0,    0,    8,    7,    1,    0,    5,    0,    0,   16,

       15,    3,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   49,    0,    0,    0,    0,   31,   18,
        4,    0,    0,    0,   14,    0,    0,    0,    0,    0,
        0,   51,    0,   18,   18,    9,    0,    0,    0,    0,
        0,    0,    0,   18,    2,    0,    0,    0,    0,    0,
       18,    0,   13,    0,    0,    0,    0,    0,   12,    0,
       33,    0,    0,   53,   11,    0,   10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    3,    4,
        2,    2,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    5,    6,    7,    8,    2,    9,   10,   11,
       12,   13,    2,   14,   15,   16,   17,   18,   18,   18,
       19,   18,   18,   18,   18,   20,   18,   21,   22,   23,
       24,   25,    2,    2,   26,   26,   26,   26,   26,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
        2,    2,    2,    2,   28,    2,   29,   26,   30,   31,

       32,   33,   34,   35,   36,   27,   27,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       27,   27,   50,    2,   51,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    1,    1,    3,    3,    1,    4,    4,    4,
        1,    1,    5,    1,    1,    4,    3,    3,    4,    4,
        4,    4,    4,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[490] =
    {   0,
        0,    0,   51,    0,  102,    0,  153,    0,  202,  251,
      302,    0,  351,    0,    0,    0, 1163, 1164,  206,  210,
      211, 1164,  209, 1164, 1164, 1164, 1164, 1145, 1164, 1151,
      197,  206,  211,  212,  216,  226, 1164, 1164,  220,  224,
     1136,  225, 1164,  232, 1164, 1164, 1164, 1142, 1134, 1164,
     1133, 1117, 1120, 1122, 1116, 1112, 1112, 1107, 1117, 1113,
     1112, 1164, 1164, 1164, 1142,  220, 1135,  240,  243, 1140,
      239, 1118, 1164, 1164, 1132,  226,  363,  386,  394,  252,
      360, 1124, 1090, 1088,  259,  261,  256, 1164, 1128, 1127,
      267,  269,  273, 1130,  401,  278,  378,  229,  281, 1164,

     1134, 1124,  262,  348,  258,  275,  350,  289,  378,  367,
      376,  375, 1164,  415,  274, 1127,  419,  418,  418,  429,
     1164, 1164, 1164, 1101, 1095, 1086, 1085, 1085, 1164, 1164,
     1082, 1094, 1093, 1120, 1164, 1119, 1112, 1120, 1110,  428,
     1109, 1164, 1117, 1107,  420,  435, 1066, 1064,  437,  445,
      425,  455,  400,  367,  460,  425, 1069, 1068, 1066,  477,
     1164,  454, 1101, 1109, 1099,  476,  483,  487,  461,  463,
      469,  470, 1098,  503,  460, 1062, 1061, 1059,  509, 1094,
     1083,  493,  494,  500,  524,  528,  530, 1164,  516,  352,
      519,  531,  536,  556,  541,  490,  535,  538, 1092,  567,

      508, 1056, 1055, 1053,  584, 1164, 1061, 1067, 1064,  555,
     1049, 1055, 1050, 1082, 1071, 1080, 1069,  577,  551,  546,
      562,  560,  580,    0, 1047, 1047, 1064, 1045, 1074, 1063,
      590,  563, 1037, 1036, 1034,  599,  636,  573,  507,  607,
      608,  605,    0, 1038, 1038, 1055, 1036,  621,  642,  618,
      632, 1056,  603,  605,  625, 1027, 1033, 1023, 1042, 1034,
      607, 1029,  599, 1025, 1038,  655,  640,  642,  650,  654,
      637, 1021, 1020, 1018,  673,  686,  579,  643,  660,  681,
      668,    0, 1022, 1022, 1039, 1020,  671,  693,  628, 1028,
     1026, 1164,  705, 1014, 1164, 1024, 1036, 1035,  706,  718,

      666,  692,  698,  694, 1031, 1008, 1006, 1031,  721,    0,
     1008, 1008, 1025, 1006, 1023,  685,  697, 1022,  999,  997,
      741,  727,  707,  710,  729,  744, 1031,  736,  684,  752,
     1006,  993, 1002, 1000,  992,  986,  995,  988, 1001,  993,
      984,  986, 1164, 1016, 1015, 1014,  751,    0,  984,  984,
     1001,  982,  773,  752,  762,  999,  976,  974,  763,  770,
      768,  772,  754,  997,  978, 1164,  977, 1164, 1005, 1004,
      800,  780,  776, 1003,  990,  967,  965,  819,  824,  773,
      775,  794,  785,  778,  988,  817,  996, 1164,  968,  962,
      961,  959, 1164, 1164, 1164,  972, 1164,  970,  973, 1164,

     1164, 1164,  978,  955,  953,  841,  846,  805,  830,  806,
      831,  976,  965, 1164,  862,  843,  845,  776, 1164,  857,
     1164,  950,  949,  961, 1164,  960,  980,  855,  882,  854,
      858, 1164,  961,  979,  830, 1164,  944,  976,  939,  973,
      944,  954,  905,  791, 1164,  898,  879,  864,  859,  844,
      864,  865, 1164,  842,  852,  847,  812,  822, 1164,  773,
     1164,  737,  661, 1164, 1164,  531, 1164, 1164,  915,  920,
      925,  928,  932,  937,  942,  945,  947,  951,  955,  958,
      962,  967,  972,  977,  563,  489,  402,  369,  293
    } ;

static yyconst flex_int16_t yy_def[490] =
    {   0,
      468,    1,  468,    3,  468,    5,  468,    7,  469,  469,
      468,   11,    3,   13,   13,   13,  468,  468,  468,  468,
      470,  468,  471,  468,  468,  468,  468,  468,  468,  472,
      472,  472,  472,  472,  472,  472,  468,  468,  468,  468,
      468,  473,  468,  474,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  475,  468,  476,  468,  468,  475,
      468,  468,  468,  468,  477,  478,  478,  478,  479,  468,
      478,  468,  468,  468,  468,  468,  468,  468,  480,  468,
      468,  470,  481,  468,  475,  471,  468,  475,  471,  468,

      468,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  468,  468,  473,  482,  468,  475,  474,  468,  475,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  475,  468,  475,  468,  468,  476,  468,
      468,  468,  468,  477,  478,  468,  468,  468,  478,  479,
      478,  475,  475,  475,  468,  468,  468,  468,  468,  479,
      468,  468,  468,  468,  480,  481,  468,  475,  475,  475,
      475,  475,  468,  468,  468,  468,  468,  468,  483,  472,
      468,  472,  472,  472,  468,  472,  468,  468,  472,  472,
      472,  482,  468,  475,  475,  475,  475,  475,  468,  468,

      468,  468,  468,  468,  484,  468,  468,  468,  468,  468,
      468,  468,  468,  476,  468,  477,  468,  475,  475,  475,
      475,  475,  468,  485,  468,  468,  468,  468,  480,  468,
      468,  468,  468,  468,  468,  475,  475,  475,  475,  475,
      475,  468,  486,  468,  468,  468,  468,  471,  475,  475,
      471,  468,  472,  472,  472,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  472,  472,  472,  468,
      468,  468,  468,  468,  475,  237,  475,  475,  475,  475,
      468,  487,  468,  468,  468,  468,  474,  475,  475,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  475,  237,

      475,  475,  475,  475,  485,  468,  468,  468,  468,  488,
      468,  468,  468,  468,  237,  475,  475,  486,  468,  468,
      475,  475,  475,  475,  475,  471,  468,  472,  472,  472,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  489,  468,  468,
      468,  468,  237,  475,  475,  487,  468,  468,  475,  475,
      475,  475,  475,  468,  468,  468,  468,  468,  468,  468,
      237,  475,  475,  468,  488,  468,  468,  475,  237,  475,
      475,  475,  475,  471,  468,  472,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  489,  468,  468,  475,  237,  475,  475,  475,
      475,  468,  468,  468,  237,  475,  475,  471,  468,  472,
      468,  468,  468,  468,  468,  468,  468,  468,  237,  475,
      475,  468,  468,  472,  472,  468,  468,  468,  468,  468,
      468,  468,  468,  472,  468,  468,  468,  468,  468,  468,
      472,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,    0,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468
    } ;

static yyconst flex_int16_t yy_nxt[1216] =
    {   0,
       18,   18,   19,   20,   18,   21,   18,   22,   18,   23,
       24,   25,   26,   27,   18,   18,   28,   18,   18,   18,
       18,   18,   29,   18,   18,   30,   30,   18,   30,   31,
       32,   30,   33,   30,   30,   34,   30,   30,   35,   30,
       30,   30,   30,   30,   36,   30,   30,   30,   30,   37,
       38,   18,   18,   39,   40,   41,   42,   18,   43,   18,
       44,   18,   45,   46,   47,   18,   18,   48,   18,   18,
       18,   18,   18,   49,   50,   51,   18,   18,   18,   52,
       53,   54,   55,   56,   18,   18,   57,   18,   18,   18,
       58,   18,   18,   59,   18,   60,   18,   18,   61,   18,

       62,   63,   18,   18,   18,   64,   18,   65,   18,   18,
       18,   66,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   67,   67,   18,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   18,   18,   18,   18,   68,   69,   18,   70,   18,
       18,   18,   71,   18,   18,   18,   18,   18,   18,   72,
       18,   18,   18,   18,   18,   18,   73,   74,   75,   75,
       18,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   18,   18,   77,   78,  101,   79,   91,   91,
       80,   81,   91,   91,   93,  101,   94,   97,   98,   95,
      101,  101,  112,  112,   82,  101,  112,  112,  115,  136,
      116,  103,  135,  117,  146,  101,   99,  104,  179,  105,
      119,  120,  140,  140,  108,  140,  140,  137,  136,  106,
      107,   83,   84,   77,   78,  109,   79,  110,  155,   80,
       81,  162,  162,  162,  162,  136,  141,  101,  111,   91,
       91,  101,   93,   82,   94,  147,  148,   95,   94,  116,
      156,  167,  193,  163,  101,  157,   97,  173,  158,   97,
      180,  187,  187,  159,  184,  185,  403,  182,  101,  188,

       83,   84,   18,   18,   85,   86,   18,   65,   18,   18,
       18,   87,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   88,   89,   89,   18,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   18,   18,   18,   64,   18,   65,  101,   18,  101,
       90,  101,   18,   18,   18,  149,  149,   18,  146,  160,
      135,  146,  375,   18,   18,   18,  101,  112,  112,   18,
       18,   18,   18,   18,  174,  101,   18,  101,  149,  149,
       18,  183,  186,   18,  146,   18,  268,  151,   18,  145,

       18,   18,  152,  135,  135,  356,  175,  168,  189,  147,
      148,  176,  147,  148,  177,  190,  134,  150,  115,  178,
      116,  191,  135,  117,  200,  194,  119,  199,  146,  169,
      140,  140,  135,  146,  170,  147,  148,  171,  205,  149,
      149,  155,  172,  153,  154,  146,  201,  195,  151,  150,
      145,  202,  196,  152,  203,  197,  162,  162,  135,  204,
      198,  218,  225,  156,  135,  226,  135,  134,  157,  147,
      148,  158,  135,  135,  147,  148,  159,  223,  223,  223,
      151,   94,  145,  219,  167,  152,  147,  148,  220,  231,
      135,  221,  318,  135,  153,  154,  222,  244,  238,  134,

      245,  239,  101,  101,  236,  236,  236,  240,  224,  101,
      135,  232,  248,  240,   96,  241,  233,  249,  250,  234,
      242,  242,  242,  254,  235,  101,  153,  154,  101,  253,
      266,  266,  187,  187,  279,  237,  116,  101,  135,  193,
      188,  135,  270,  255,  135,  283,  316,  267,  284,  135,
      269,  243,  256,  257,  135,  258,  259,  293,  293,  135,
      260,  261,  262,  135,  271,  135,  305,  263,  264,  272,
      265,  467,  273,  275,  275,  275,  135,  274,  277,  279,
      135,  278,  135,  280,  281,  281,  281,  287,  301,  118,
      303,  302,  288,  289,  299,  299,  299,  223,  223,  223,

      311,  145,  135,  312,  276,  304,  303,  309,  309,  309,
      135,  135,  101,  240,  101,  282,  236,  236,  236,  279,
       92,  135,  242,  242,  242,  300,   96,  179,   92,   97,
      173,  135,  326,  328,  101,  336,  329,  205,  310,  135,
       97,  173,  337,  339,  340,  135,  135,  317,  321,  101,
      344,  101,  345,  315,  315,  315,  330,  266,  266,  101,
      346,  315,  343,  135,  315,  315,  315,  315,  315,  135,
      322,  347,  347,  347,  349,  323,  135,  350,  324,  119,
      199,  114,  354,  325,  135,  281,  281,  281,  135,  118,
      275,  275,  275,  101,  114,  135,  135,  135,  466,  359,

      135,  135,  348,  353,  353,  353,  303,  293,  293,  135,
      135,  353,  366,  135,  353,  353,  353,  353,  353,  150,
      355,  360,  386,  299,  299,  299,  361,  150,  240,  362,
      135,  372,  135,  373,  363,  371,  371,  371,  309,  309,
      309,  240,  166,  371,  135,  101,  371,  371,  371,  371,
      371,  382,   97,  173,  382,  135,  385,  135,  378,  378,
      378,  101,  387,  384,  380,  135,  135,  381,  347,  347,
      347,  135,  192,  135,  383,  135,  135,  465,  135,  135,
      406,  406,  406,  135,   97,  434,   97,  173,  135,  379,
      353,  353,  353,  464,  114,  279,  418,  135,  353,  411,

      101,  353,  353,  353,  353,  353,  279,  408,  135,  135,
      409,  407,  410,  382,  416,  179,  410,  371,  371,  371,
      303,  150,  135,  303,  417,  371,  101,  205,  371,  371,
      371,  371,  371,  135,  135,  451,  378,  378,  378,  101,
      179,  415,  415,  415,  135,  410,  135,  420,  135,  415,
      463,  462,  415,  415,  415,  415,  415,  135,  406,  406,
      406,  135,  205,  429,  429,  429,  101,  461,  444,  430,
      431,  429,  460,  101,  429,  429,  429,  429,  429,  415,
      415,  415,  459,  179,  456,  435,  382,  415,  455,  382,
      415,  415,  415,  415,  415,  441,  454,  410,  442,  429,

      429,  429,  410,  205,  453,  457,  452,  429,  458,  421,
      429,  429,  429,  429,  429,   76,   76,   76,   76,   76,
       92,   92,   92,   92,   92,   96,   96,   96,   96,   96,
      102,  102,  114,  114,  114,  114,  114,  118,  118,  118,
      118,  118,  134,  450,  134,  134,  134,  139,  139,  144,
      144,  145,  145,  145,  145,  150,  150,  150,  150,  150,
      165,  165,  166,  166,  166,  166,  166,  192,  192,  192,
      192,  192,  179,  179,  179,  179,  179,  205,  205,  205,
      205,  205,  449,  448,  402,  447,  446,  445,  251,  443,
      440,  439,  438,  437,  436,  433,  432,  351,  351,  192,

      428,  427,  426,  425,  424,  423,  422,  421,  419,  313,
      313,  166,  165,  144,  139,  414,  413,  412,  285,  285,
      118,  405,  192,  404,  351,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      102,  246,  246,   96,   92,  377,  166,  376,  313,  374,
      227,  227,  145,  370,  369,  368,  367,  365,  364,  358,
      118,  357,  285,  352,  351,  351,  342,  341,  338,  335,
      334,  333,  332,  331,  327,  320,   96,  319,  246,  314,
      313,  313,  308,  164,  307,  145,  306,  227,  298,  143,
      297,  138,  296,  295,  294,  292,  291,  290,  286,  285,

      285,  118,  252,  251,  247,  246,  246,   96,  164,  230,
      229,  228,  227,  227,  145,  145,  143,  217,  216,  138,
      215,  214,  135,  135,  213,  212,  211,  210,  209,  208,
      207,  206,  192,  101,  181,  166,  136,  164,  145,  145,
      161,  143,  142,  135,  138,  135,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  113,
      101,  100,  468,   17,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468
    } ;

static yyconst flex_int16_t yy_chk[1216] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    9,    9,   31,    9,   19,   19,
        9,    9,   20,   20,   21,   32,   21,   23,   23,   21,
       33,   34,   39,   39,    9,   35,   40,   40,   42,   66,
       42,   31,   98,   42,   76,   36,   23,   32,   98,   33,
       44,   44,   68,   68,   34,   69,   69,   66,   71,   33,
       33,    9,    9,   10,   10,   35,   10,   36,   80,   10,
       10,   85,   85,   86,   86,   87,   71,  105,   36,   91,
       91,  103,   92,   10,   92,   76,   76,   92,   93,  115,
       80,   93,  115,   87,  106,   80,   96,   96,   80,   99,
       99,  108,  108,   80,  105,  106,  489,  103,  108,  108,

       10,   10,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   13,   13,   13,   13,  104,   13,  107,
       13,  190,   13,   13,   13,   77,   77,   13,   81,   81,
      154,   77,  488,   13,   13,   13,  110,  112,  112,   13,
       13,   13,   13,   13,   97,  111,   13,  109,   78,   78,
       13,  104,  107,   13,   78,   13,  190,   79,   13,   79,

       13,   13,   79,  153,   95,  487,   97,   95,  109,   81,
       81,   97,   77,   77,   97,  110,   79,  154,  114,   97,
      114,  111,  117,  114,  119,  117,  118,  118,  145,   95,
      140,  140,  120,  151,   95,   78,   78,   95,  120,  149,
      149,  146,   95,   79,   79,  149,  119,  117,  150,  153,
      150,  119,  117,  150,  119,  117,  162,  162,  152,  119,
      117,  152,  156,  146,  169,  156,  170,  150,  146,  145,
      145,  146,  171,  172,  151,  151,  146,  155,  155,  155,
      160,  166,  160,  152,  166,  160,  149,  149,  152,  167,
      168,  152,  486,  196,  150,  150,  152,  175,  169,  160,

      175,  169,  182,  183,  168,  168,  168,  170,  155,  184,
      239,  167,  179,  171,  179,  172,  167,  179,  179,  167,
      174,  174,  174,  183,  167,  189,  160,  160,  191,  182,
      186,  186,  187,  187,  196,  168,  192,  186,  197,  192,
      187,  198,  193,  184,  195,  201,  239,  189,  201,  220,
      191,  174,  185,  185,  219,  185,  185,  210,  210,  194,
      185,  185,  185,  222,  193,  221,  485,  185,  185,  193,
      185,  466,  193,  194,  194,  194,  238,  193,  195,  197,
      218,  195,  277,  198,  200,  200,  200,  205,  219,  205,
      220,  219,  205,  205,  218,  218,  218,  223,  223,  223,

      232,  223,  236,  232,  194,  222,  221,  231,  231,  231,
      240,  241,  253,  238,  254,  200,  236,  236,  236,  277,
      236,  250,  242,  242,  242,  218,  242,  250,  240,  248,
      248,  289,  251,  253,  255,  261,  254,  289,  231,  237,
      251,  251,  261,  263,  263,  249,  278,  241,  249,  267,
      267,  268,  268,  237,  237,  237,  255,  266,  266,  269,
      269,  237,  266,  279,  237,  237,  237,  237,  237,  301,
      249,  270,  270,  270,  271,  249,  275,  271,  249,  287,
      287,  279,  278,  249,  280,  281,  281,  281,  316,  281,
      275,  275,  275,  329,  275,  302,  288,  304,  463,  288,

      317,  303,  270,  276,  276,  276,  301,  293,  293,  299,
      323,  276,  293,  324,  276,  276,  276,  276,  276,  303,
      280,  288,  329,  299,  299,  299,  288,  299,  316,  288,
      322,  302,  325,  304,  288,  300,  300,  300,  309,  309,
      309,  317,  309,  300,  321,  328,  300,  300,  300,  300,
      300,  323,  326,  326,  324,  354,  328,  363,  321,  321,
      321,  330,  330,  326,  322,  355,  359,  322,  347,  347,
      347,  361,  347,  360,  325,  362,  380,  462,  381,  373,
      359,  359,  359,  372,  418,  418,  384,  384,  383,  321,
      353,  353,  353,  460,  353,  354,  384,  382,  353,  363,

      444,  353,  353,  353,  353,  353,  355,  360,  408,  410,
      360,  359,  361,  380,  381,  382,  362,  371,  371,  371,
      373,  371,  378,  372,  383,  371,  386,  410,  371,  371,
      371,  371,  371,  409,  411,  444,  378,  378,  378,  435,
      378,  379,  379,  379,  406,  408,  416,  386,  417,  379,
      458,  457,  379,  379,  379,  379,  379,  430,  406,  406,
      406,  431,  406,  407,  407,  407,  420,  456,  435,  409,
      411,  407,  455,  451,  407,  407,  407,  407,  407,  415,
      415,  415,  454,  415,  451,  420,  416,  415,  450,  417,
      415,  415,  415,  415,  415,  428,  449,  430,  428,  429,

      429,  429,  431,  429,  448,  452,  447,  429,  452,  446,
      429,  429,  429,  429,  429,  469,  469,  469,  469,  469,
      470,  470,  470,  470,  470,  471,  471,  471,  471,  471,
      472,  472,  473,  473,  473,  473,  473,  474,  474,  474,
      474,  474,  475,  443,  475,  475,  475,  476,  476,  477,
      477,  478,  478,  478,  478,  479,  479,  479,  479,  479,
      480,  480,  481,  481,  481,  481,  481,  482,  482,  482,
      482,  482,  483,  483,  483,  483,  483,  484,  484,  484,
      484,  484,  442,  441,  440,  439,  438,  437,  434,  433,
      427,  426,  424,  423,  422,  413,  412,  405,  404,  403,

      399,  398,  396,  392,  391,  390,  389,  387,  385,  377,
      376,  375,  374,  370,  369,  367,  365,  364,  358,  357,
      356,  352,  351,  350,  349,  346,  345,  344,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      327,  320,  319,  318,  315,  314,  313,  312,  311,  308,
      307,  306,  305,  298,  297,  296,  294,  291,  290,  286,
      285,  284,  283,  274,  273,  272,  265,  264,  262,  260,
      259,  258,  257,  256,  252,  247,  246,  245,  244,  235,
      234,  233,  230,  229,  228,  227,  226,  225,  217,  216,
      215,  214,  213,  212,  211,  209,  208,  207,  204,  203,

      202,  199,  181,  180,  178,  177,  176,  173,  165,  164,
      163,  159,  158,  157,  148,  147,  144,  143,  141,  139,
      138,  137,  136,  134,  133,  132,  131,  128,  127,  126,
      125,  124,  116,  102,  101,   94,   90,   89,   84,   83,
       82,   75,   72,   70,   67,   65,   61,   60,   59,   58,
       57,   56,   55,   54,   53,   52,   51,   49,   48,   41,
       30,   28,   17,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,

      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  468
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[79] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "query_lexer.l"
/*
 | Author: Stefanie Scherzinger;
 |         Gunnar Jehl (multi-step paths/aggregate functions/optimizations) 
 ===========================================================================
 ===========================================================================
 | Software License Agreement (BSD License)
 | 
 | Copyright (c) 2006-2007, Saarland University Database Group 
 | All rights reserved.
 |
 | Redistribution and use of this software in source and binary forms,
 | with or without modification, are permitted provided that the following
 | conditions are met:
 | 
 | * Redistributions of source code must retain the above
 |   copyright notice, this list of conditions and the
 |   following disclaimer.
 |
 | * Redistributions in binary form must reproduce the above
 |   copyright notice, this list of conditions and the
 |   following disclaimer in the documentation and/or other
 |   materials provided with the distribution.
 |
 | * Neither the name the of Saarland University Database Group nor the names 
 |   of its contributors may be used to endorse or promote products derived 
 |   from this software without specific prior written permission of the
 |   Saarland University Database Group.
 | 
 | THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 | AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 | IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 | ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 | LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 | CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 | SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 | INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 | CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 | ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 | POSSIBILITY OF SUCH DAMAGE.
*/
/*! @file
 *  @brief LEXER.
 *  @details LEXER.
 *  @author Stefanie Scherzinger
 *  @author Gunnar Jehl (multi-step paths/aggregate functions/optimizations)
 *  @version 1.01b
 *  @license Software License Agreement (BSD License)
 */
#line 52 "query_lexer.l"

using namespace std;

#include <sstream>
#include <vector>
#include <list>
#include "typeenums.h"
#include "error.h"

// forward declarations
class Expression;
class PathExpression;
class PathStepExpression;
class VarExpression;
class ConstExpression;
class CondExpression;
class OperandExpression;
class VarStepExpression;
class AggregateFunctExpression;

typedef list< pair<VarExpression*, Expression*> > var_list_type;

#include "query_parser.h"

extern const char * xquery_file;

void yyerror(const char *);

/* own stack for maintaining lexer start conditions */
/* (different semantics from yy_push_state); */
vector<int> stack;

void push_state(int state);
void pop_state();

/* transform "string" to string */
char * extract_const_string(const char * text);

/* error message if a feature not implemented */
void feature_not_implemented(const char * text);

/* Lexer rules adapted from Galax */
/* Whitespace */
/* XML character sets */
/* XML names */
/* String Literals */


#line 993 "query_lexer.C"

#define INITIAL 0
#define OPERATOR 1
#define S_VARNAME 2
#define START_TAG 3
#define ELEMENT_CONTENT 4
#define END_TAG 5
#define QUOT_ATTRIBUTE_CONTENT 6
#define APOS_ATTRIBUTE_CONTENT 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 134 "query_lexer.l"


#line 1185 "query_lexer.C"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 469 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1164 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 136 "query_lexer.l"
{
              return NOT;
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 140 "query_lexer.l"
{
              return EXISTS;
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 144 "query_lexer.l"
{
                          BEGIN(OPERATOR);
                          return XTRUE;
                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 149 "query_lexer.l"
{
                            BEGIN(OPERATOR);
                            return XFALSE;
                          }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 154 "query_lexer.l"
{
              return SUM;
            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 158 "query_lexer.l"
{
              return AVG;
            }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 162 "query_lexer.l"
{
              return MIN;
            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 166 "query_lexer.l"
{
              return MAX;
            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 170 "query_lexer.l"
{
                return COUNT;
              }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 174 "query_lexer.l"
{
                      return STDDEV_SAMP;
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 178 "query_lexer.l"
{
                     return STDDEV_POP;
                   }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 182 "query_lexer.l"
{
                   return VAR_SAMP;
                 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 186 "query_lexer.l"
{
                  return VAR_POP;
                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 190 "query_lexer.l"
{
               return LIST;
             }																														
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 194 "query_lexer.l"
{
              BEGIN(OPERATOR);
              return XP_TEXT;
            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 199 "query_lexer.l"
{
              BEGIN(OPERATOR);
              return XP_NODE;
            }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 204 "query_lexer.l"
{
                    }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 207 "query_lexer.l"
{
             BEGIN(OPERATOR);
             yylval.str = strdup(yytext);
             return QNAME;
           }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 213 "query_lexer.l"
{
                     BEGIN(OPERATOR);
                     yylval.str = extract_const_string(yytext);
                     return CONSTSTRING;
                   }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 219 "query_lexer.l"
{
         BEGIN(OPERATOR);
         return BCLOSE;
       }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 224 "query_lexer.l"
{
         BEGIN(OPERATOR);
         return NT_STAR;
       }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 229 "query_lexer.l"
{
         BEGIN(S_VARNAME);
         return VAR_SIGN;   
       }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 234 "query_lexer.l"
{
                              /* BEGIN(S_VARNAME); */
                              unput('$');
                              return FOR;
                            }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 240 "query_lexer.l"
{
         push_state(OPERATOR);
         BEGIN(START_TAG);
         return RELOP_LT;
       }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 246 "query_lexer.l"
{
         pop_state();
         return CBCLOSE;
       }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 251 "query_lexer.l"
{
         push_state(OPERATOR);
         return CBOPEN;       
       }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 256 "query_lexer.l"
{
         return COMMA;
       }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 260 "query_lexer.l"
{
         return BOPEN;
       }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 264 "query_lexer.l"
{
                         unput('(');
                         return IF;
                       }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 269 "query_lexer.l"
{
         return SLASH;
       }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 273 "query_lexer.l"
{
               return CHILD;
             }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 277 "query_lexer.l"
{
          return DSLASH;
        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 281 "query_lexer.l"
{
                    return DESCENDANT;
                  }
	YY_BREAK

case 34:
YY_RULE_SETUP
#line 286 "query_lexer.l"
{
             push_state(OPERATOR);
             BEGIN(0);
             return CBOPEN;
           }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 292 "query_lexer.l"
{
                BEGIN(0);
                return THEN;
              }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 297 "query_lexer.l"
{
                BEGIN(0);
                return ELSE;
              }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 302 "query_lexer.l"
{
               BEGIN(0);
               return AND;
             }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 307 "query_lexer.l"
{
             BEGIN(0);
             return COMMA;
           }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 312 "query_lexer.l"
{
             BEGIN(0);
             return RELOP_EQ;
           }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 317 "query_lexer.l"
{
              BEGIN(0);
              return RELOP_NEQ;
            }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 322 "query_lexer.l"
{
             BEGIN(0);
             return RELOP_LT;
           }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 327 "query_lexer.l"
{
             BEGIN(0);
             return RELOP_GT;
           }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 332 "query_lexer.l"
{
              BEGIN(0);
              return RELOP_LEQ;
            }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 337 "query_lexer.l"
{
              BEGIN(0);
              return RELOP_GEQ;
            }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 342 "query_lexer.l"
{
              BEGIN(0);
              return IN;
            }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 347 "query_lexer.l"
{
             BEGIN(0);
             return NT_STAR;
           }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 352 "query_lexer.l"
{
              BEGIN(0);
              return OR;
            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 357 "query_lexer.l"
{
                 BEGIN(0);
                 return WHERE;
               }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 362 "query_lexer.l"
{
                  BEGIN(0);
                  return XRETURN;
                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 367 "query_lexer.l"
{
             BEGIN(0);
             return SLASH;
           }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 372 "query_lexer.l"
{
                   BEGIN(0);
                   return CHILD;
                 }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 377 "query_lexer.l"
{
              BEGIN(0);
              return DSLASH;
            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 382 "query_lexer.l"
{
                        BEGIN(0);
                        return DESCENDANT;
                      }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 387 "query_lexer.l"
{
             pop_state();
             return CBCLOSE;
           }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 392 "query_lexer.l"
{
             BEGIN(S_VARNAME);
             return VAR_SIGN;
           }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 397 "query_lexer.l"
{
                                  /* BEGIN(S_VARNAME); */
                                  unput('$');
                                  return FOR;
                                }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 403 "query_lexer.l"
{
             return BCLOSE;
           }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 407 "query_lexer.l"
{
                         yylval.str = extract_const_string(yytext);
                         return CONSTSTRING;
                       }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 412 "query_lexer.l"
{
              /* ignore whitespace */
            }    
	YY_BREAK

case 60:
YY_RULE_SETUP
#line 417 "query_lexer.l"
{
                      BEGIN(OPERATOR);
                      yylval.str = strdup(yytext);
                      return VARNAME;
                     }
	YY_BREAK

case 61:
YY_RULE_SETUP
#line 424 "query_lexer.l"
{
              pop_state();
              return GTSLASH;
            }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 429 "query_lexer.l"
{
             BEGIN(ELEMENT_CONTENT);
             return RELOP_GT;
           }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 434 "query_lexer.l"
{
              BEGIN(QUOT_ATTRIBUTE_CONTENT);
              feature_not_implemented("attributes");
            }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 439 "query_lexer.l"
{
             BEGIN(APOS_ATTRIBUTE_CONTENT);
             feature_not_implemented("attributes");
           }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 444 "query_lexer.l"
{
             feature_not_implemented("attributes");
           }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 448 "query_lexer.l"
{
            }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 451 "query_lexer.l"
{
                 yylval.str = strdup(yytext);
                 return QNAME;
               }          
	YY_BREAK


case 68:
YY_RULE_SETUP
#line 458 "query_lexer.l"
{
              BEGIN(END_TAG);
              return LTSLASH;
            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 463 "query_lexer.l"
{
             push_state(ELEMENT_CONTENT);
             BEGIN(0);
             return CBOPEN;
           }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 469 "query_lexer.l"
{
             push_state(ELEMENT_CONTENT);
             BEGIN(START_TAG);
             return RELOP_LT;
           }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 475 "query_lexer.l"
{
              /* ignore whitespace */
            }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 479 "query_lexer.l"
{
                          char * newstr = new char[strlen(yytext) + 1];
                          unsigned lastpos = 0;
                          bool last_skipped = false;

                          for(unsigned i=0; i<strlen(yytext); i++) {
                            if (i==0) {
                              newstr[0] = yytext[0];
                              lastpos = 0;
                            } else {
                              if(!((yytext[i-1]=='{' && yytext[i]=='{') || (yytext[i-1]=='}' && yytext[i]=='}')) || last_skipped) {
                                newstr[++lastpos] = yytext[i];
                                last_skipped = false;
                              } else {
                                last_skipped = true;
                              }
                            }
                          }
                          newstr[lastpos+1] = '\0';

                          yylval.str = newstr;
                          return ELEMENTCONTENT;
                        }               
	YY_BREAK


case 73:
YY_RULE_SETUP
#line 505 "query_lexer.l"
{
             pop_state();
             return RELOP_GT;
           }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 510 "query_lexer.l"
{
            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 513 "query_lexer.l"
{
                 yylval.str = strdup(yytext);
                 return QNAME;
               }      
	YY_BREAK

case 76:
YY_RULE_SETUP
#line 519 "query_lexer.l"
{
          /* report errors */
          yyerror("Call Error");   
        }
	YY_BREAK
case 77:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 524 "query_lexer.l"
{
                             yyerror("Unterminated String");
                           }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 528 "query_lexer.l"
ECHO;
	YY_BREAK
#line 1920 "query_lexer.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(OPERATOR):
case YY_STATE_EOF(S_VARNAME):
case YY_STATE_EOF(START_TAG):
case YY_STATE_EOF(ELEMENT_CONTENT):
case YY_STATE_EOF(END_TAG):
case YY_STATE_EOF(QUOT_ATTRIBUTE_CONTENT):
case YY_STATE_EOF(APOS_ATTRIBUTE_CONTENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 469 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 469 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 468);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 528 "query_lexer.l"



int yywrap(void) {
  return 1;
}

void pop_state() {
  /* if (! stack.empty()) */
  /* yyerror("Syntax Error"); */

  int resume_state = stack.back();
  stack.pop_back();
  BEGIN(resume_state);
}

void push_state(int state) {
  stack.push_back(state);
}

char * extract_const_string(const char * text) {
  char * str  = strncpy(new char[strlen(text) - 1 ], yytext+1, strlen(text) - 2);
  str[strlen(text)-2] = '\0';

  return str;
}

void yyerror(const char * text) {
  std::ostringstream o;
  o << "Query File \"" << xquery_file << "\" Error: In Line " << yylineno << " => "  << text
       << " (\"" << yytext << "\")." << endl;
  Error::getInstance()->throwError(o.str().c_str());
}

void feature_not_implemented(const char * text) {
  std::ostringstream o;
  o << "Query File \"" << xquery_file << "\" Error: In Line " << yylineno << " => Feature \""
       << text << "\" Not Yet Implemented.";
  Error::getInstance()->throwError(o.str().c_str());
}

