
#line 3 "lex.yyxml.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyxmlconst const
#else
#define yyxmlconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yyxml_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yyxml_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyxmlrestart(yyxmlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yyxml_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yyxml_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyxmlleng;

extern FILE *yyxmlin, *yyxmlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyxmlless(n) \
	do \
		{ \
		/* Undo effects of setting up yyxmltext. */ \
        int yyxmlless_macro_arg = (n); \
        YY_LESS_LINENO(yyxmlless_macro_arg);\
		*yyxml_cp = (yyxml_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yyxml_c_buf_p) = yyxml_cp = yyxml_bp + yyxmlless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yyxmltext again */ \
		} \
	while ( 0 )

#define unput(c) yyxmlunput( c, (yyxmltext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yyxml_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yyxml_buffer_state
	{
	FILE *yyxml_input_file;

	char *yyxml_ch_buf;		/* input buffer */
	char *yyxml_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yyxml_size_t yyxml_buf_size;

	/* Number of characters read into yyxml_ch_buf, not including EOB
	 * characters.
	 */
	int yyxml_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yyxml_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yyxml_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyxml_at_bol;

    int yyxml_bs_lineno; /**< The line count. */
    int yyxml_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yyxml_fill_buffer;

	int yyxml_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyxmlrestart()), so that the user can continue scanning by
	 * just pointing yyxmlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yyxml_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yyxml_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yyxml_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yyxml_buffer_stack) \
                          ? (yyxml_buffer_stack)[(yyxml_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yyxml_buffer_stack)[(yyxml_buffer_stack_top)]

/* yyxml_hold_char holds the character lost when yyxmltext is formed. */
static char yyxml_hold_char;
static int yyxml_n_chars;		/* number of characters read into yyxml_ch_buf */
int yyxmlleng;

/* Points to current character in buffer. */
static char *yyxml_c_buf_p = (char *) 0;
static int yyxml_init = 0;		/* whether we need to initialize */
static int yyxml_start = 0;	/* start state number */

/* Flag which is used to allow yyxmlwrap()'s to do buffer switches
 * instead of setting up a fresh yyxmlin.  A bit of a hack ...
 */
static int yyxml_did_buffer_switch_on_eof;

void yyxmlrestart (FILE *input_file  );
void yyxml_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yyxml_create_buffer (FILE *file,int size  );
void yyxml_delete_buffer (YY_BUFFER_STATE b  );
void yyxml_flush_buffer (YY_BUFFER_STATE b  );
void yyxmlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yyxmlpop_buffer_state (void );

static void yyxmlensure_buffer_stack (void );
static void yyxml_load_buffer_state (void );
static void yyxml_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yyxml_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yyxml_scan_buffer (char *base,yyxml_size_t size  );
YY_BUFFER_STATE yyxml_scan_string (yyxmlconst char *yyxml_str  );
YY_BUFFER_STATE yyxml_scan_bytes (yyxmlconst char *bytes,int len  );

void *yyxmlalloc (yyxml_size_t  );
void *yyxmlrealloc (void *,yyxml_size_t  );
void yyxmlfree (void *  );

#define yyxml_new_buffer yyxml_create_buffer

#define yyxml_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyxmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yyxml_create_buffer(yyxmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyxml_is_interactive = is_interactive; \
	}

#define yyxml_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyxmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yyxml_create_buffer(yyxmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyxml_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyxml_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyxmlin = (FILE *) 0, *yyxmlout = (FILE *) 0;

typedef int yyxml_state_type;

extern int yyxmllineno;

int yyxmllineno = 1;

extern char *yyxmltext;
#define yyxmltext_ptr yyxmltext

static yyxml_state_type yyxml_get_previous_state (void );
static yyxml_state_type yyxml_try_NUL_trans (yyxml_state_type current_state  );
static int yyxml_get_next_buffer (void );
static void yyxml_fatal_error (yyxmlconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yyxmltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yyxmltext_ptr) = yyxml_bp; \
	yyxmlleng = (size_t) (yyxml_cp - yyxml_bp); \
	(yyxml_hold_char) = *yyxml_cp; \
	*yyxml_cp = '\0'; \
	(yyxml_c_buf_p) = yyxml_cp;

#define YY_NUM_RULES 7
#define YY_END_OF_BUFFER 8
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yyxml_trans_info
	{
	flex_int32_t yyxml_verify;
	flex_int32_t yyxml_nxt;
	};
static yyxmlconst flex_int16_t yyxml_accept[21] =
    {   0,
        0,    0,    8,    2,    2,    6,    2,    0,    0,    0,
        0,    0,    0,    0,    3,    1,    0,    4,    5,    0
    } ;

static yyxmlconst flex_int32_t yyxml_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    5,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    6,
        1,    7,    3,    1,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1,    8,    1,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyxmlconst flex_int32_t yyxml_meta[9] =
    {   0,
        1,    1,    1,    2,    1,    3,    4,    2
    } ;

static yyxmlconst flex_int16_t yyxml_base[25] =
    {   0,
        0,    5,   16,    0,    0,    9,    0,    0,    7,   14,
        6,    3,    0,    2,   37,   37,    1,   37,   37,   37,
       22,   26,   30,   32
    } ;

static yyxmlconst flex_int16_t yyxml_def[25] =
    {   0,
       21,   21,   20,   22,   22,   20,   22,   23,   20,   20,
       23,   24,   10,   20,   20,   20,   24,   20,   20,    0,
       20,   20,   20,   20
    } ;

static yyxmlconst flex_int16_t yyxml_nxt[46] =
    {   0,
       20,    5,   20,   20,   20,    6,    5,   18,   19,   18,
        6,    8,   16,    9,   12,   20,   10,   13,   14,   20,
       15,   13,    4,    4,    4,    4,    7,    7,   20,    7,
       11,   11,   11,   17,   20,   17,    3,   20,   20,   20,
       20,   20,   20,   20,   20
    } ;

static yyxmlconst flex_int16_t yyxml_chk[46] =
    {   0,
        0,    1,    0,    0,    0,    1,    2,   17,   14,   12,
        2,    6,   11,    6,    9,    3,    6,   10,   10,    0,
       10,   10,   21,   21,   21,   21,   22,   22,    0,   22,
       23,   23,   23,   24,    0,   24,   20,   20,   20,   20,
       20,   20,   20,   20,   20
    } ;

static yyxml_state_type yyxml_last_accepting_state;
static char *yyxml_last_accepting_cpos;

extern int yyxml_flex_debug;
int yyxml_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yyxmlmore() yyxmlmore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yyxmltext;
#line 1 "sax.l"
/*
 | Author: Stefanie Scherzinger
 |         Gunnar Jehl (multi-step paths/aggregate functions/optimizations) 
 ===========================================================================
 ===========================================================================
 | Software License Agreement (BSD License)
 | 
 | Copyright (c) 2006-2007, Saarland University Database Group 
 | All rights reserved.
 |
 | Redistribution and use of this software in source and binary forms,
 | with or without modification, are permitted provided that the following
 | conditions are met:
 | 
 | * Redistributions of source code must retain the above
 |   copyright notice, this list of conditions and the
 |   following disclaimer.
 |
 | * Redistributions in binary form must reproduce the above
 |   copyright notice, this list of conditions and the
 |   following disclaimer in the documentation and/or other
 |   materials provided with the distribution.
 |
 | * Neither the name the of Saarland University Database Group nor the names 
 |   of its contributors may be used to endorse or promote products derived 
 |   from this software without specific prior written permission of the
 |   Saarland University Database Group.
 | 
 | THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 | AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 | IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 | ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 | LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 | CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 | SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 | INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 | CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 | ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 | POSSIBILITY OF SUCH DAMAGE.
*/
/*! @file
 *  @brief SAX-PARSER.
 *  @details SAX-PARSER.
 *  @author Stefanie Scherzinger
 *  @author Gunnar Jehl (multi-step paths/aggregate functions/optimizations)
 *  @version 1.01b
 *  @license Software License Agreement (BSD License)
 */
#line 50 "sax.l"

using namespace std;
 
#include <sstream>
#include "error.h"

void yyxmlerror(const char *);

void saxCharacters(const char* _text);		// PCDATA
void saxBeginElement(const char* _tag);		// opening tag
#ifdef VALIDATION
void saxEndElement(const char* _tag);		// closing tag
#else
void saxEndElement();						// closing tag
#endif // #ifdef VALIDATION
void saxBeginEndElement(const char* _tag);	// bachelor tag

#line 528 "lex.yyxml.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yyxml_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yyxmllex_destroy (void );

int yyxmlget_debug (void );

void yyxmlset_debug (int debug_flag  );

YY_EXTRA_TYPE yyxmlget_extra (void );

void yyxmlset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyxmlget_in (void );

void yyxmlset_in  (FILE * in_str  );

FILE *yyxmlget_out (void );

void yyxmlset_out  (FILE * out_str  );

int yyxmlget_leng (void );

char *yyxmlget_text (void );

int yyxmlget_lineno (void );

void yyxmlset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yyxmlwrap (void );
#else
extern int yyxmlwrap (void );
#endif
#endif

    static void yyxmlunput (int c,char *buf_ptr  );
    
#ifndef yyxmltext_ptr
static void yyxml_flex_strncpy (char *,yyxmlconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yyxml_flex_strlen (yyxmlconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyxmlinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yyxmltext, yyxmlleng, 1, yyxmlout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yyxml_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyxmlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyxmlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyxmlin))==0 && ferror(yyxmlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyxmlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyxmlterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyxmlterminate
#define yyxmlterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yyxml_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yyxmllex (void);

#define YY_DECL int yyxmllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yyxmltext and yyxmlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yyxml_state_type yyxml_current_state;
	register char *yyxml_cp, *yyxml_bp;
	register int yyxml_act;
    
#line 69 "sax.l"


#line 713 "lex.yyxml.c"

	if ( !(yyxml_init) )
		{
		(yyxml_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yyxml_start) )
			(yyxml_start) = 1;	/* first start state */

		if ( ! yyxmlin )
			yyxmlin = stdin;

		if ( ! yyxmlout )
			yyxmlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyxmlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yyxml_create_buffer(yyxmlin,YY_BUF_SIZE );
		}

		yyxml_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yyxml_cp = (yyxml_c_buf_p);

		/* Support of yyxmltext. */
		*yyxml_cp = (yyxml_hold_char);

		/* yyxml_bp points to the position in yyxml_ch_buf of the start of
		 * the current run.
		 */
		yyxml_bp = yyxml_cp;

		yyxml_current_state = (yyxml_start);
yyxml_match:
		do
			{
			register YY_CHAR yyxml_c = yyxml_ec[YY_SC_TO_UI(*yyxml_cp)];
			if ( yyxml_accept[yyxml_current_state] )
				{
				(yyxml_last_accepting_state) = yyxml_current_state;
				(yyxml_last_accepting_cpos) = yyxml_cp;
				}
			while ( yyxml_chk[yyxml_base[yyxml_current_state] + yyxml_c] != yyxml_current_state )
				{
				yyxml_current_state = (int) yyxml_def[yyxml_current_state];
				if ( yyxml_current_state >= 21 )
					yyxml_c = yyxml_meta[(unsigned int) yyxml_c];
				}
			yyxml_current_state = yyxml_nxt[yyxml_base[yyxml_current_state] + (unsigned int) yyxml_c];
			++yyxml_cp;
			}
		while ( yyxml_base[yyxml_current_state] != 37 );

yyxml_find_action:
		yyxml_act = yyxml_accept[yyxml_current_state];
		if ( yyxml_act == 0 )
			{ /* have to back up */
			yyxml_cp = (yyxml_last_accepting_cpos);
			yyxml_current_state = (yyxml_last_accepting_state);
			yyxml_act = yyxml_accept[yyxml_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yyxml_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yyxml_cp = (yyxml_hold_char);
			yyxml_cp = (yyxml_last_accepting_cpos);
			yyxml_current_state = (yyxml_last_accepting_state);
			goto yyxml_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 71 "sax.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 73 "sax.l"
{
                                      saxCharacters(yyxmltext);
                                      return 1;
                                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "sax.l"
{
									  saxBeginElement(yyxmltext);
									  return 1;
                                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 83 "sax.l"
{
									  #ifdef VALIDATION
                                      saxEndElement(yyxmltext);
									  #else
                                      saxEndElement();
									  #endif // #ifdef VALIDATION
                                      return 1;
                                    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 92 "sax.l"
{
									  saxBeginEndElement(yyxmltext);
                                      return 1;
                                    }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 97 "sax.l"
{
                                      yyxmlerror("Misparsed");
                                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 101 "sax.l"
ECHO;
	YY_BREAK
#line 851 "lex.yyxml.c"
case YY_STATE_EOF(INITIAL):
	yyxmlterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yyxml_amount_of_matched_text = (int) (yyxml_cp - (yyxmltext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yyxml_cp = (yyxml_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yyxml_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyxmlin at a new source and called
			 * yyxmllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yyxml_n_chars) = YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yyxml_input_file = yyxmlin;
			YY_CURRENT_BUFFER_LVALUE->yyxml_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yyxml_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yyxml_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yyxml_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars)] )
			{ /* This was really a NUL. */
			yyxml_state_type yyxml_next_state;

			(yyxml_c_buf_p) = (yyxmltext_ptr) + yyxml_amount_of_matched_text;

			yyxml_current_state = yyxml_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yyxml_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yyxml_next_state = yyxml_try_NUL_trans( yyxml_current_state );

			yyxml_bp = (yyxmltext_ptr) + YY_MORE_ADJ;

			if ( yyxml_next_state )
				{
				/* Consume the NUL. */
				yyxml_cp = ++(yyxml_c_buf_p);
				yyxml_current_state = yyxml_next_state;
				goto yyxml_match;
				}

			else
				{
				yyxml_cp = (yyxml_c_buf_p);
				goto yyxml_find_action;
				}
			}

		else switch ( yyxml_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yyxml_did_buffer_switch_on_eof) = 0;

				if ( yyxmlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yyxml_get_next_buffer() to have set up
					 * yyxmltext, we can now set up
					 * yyxml_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yyxml_c_buf_p) = (yyxmltext_ptr) + YY_MORE_ADJ;

					yyxml_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yyxml_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yyxml_c_buf_p) =
					(yyxmltext_ptr) + yyxml_amount_of_matched_text;

				yyxml_current_state = yyxml_get_previous_state(  );

				yyxml_cp = (yyxml_c_buf_p);
				yyxml_bp = (yyxmltext_ptr) + YY_MORE_ADJ;
				goto yyxml_match;

			case EOB_ACT_LAST_MATCH:
				(yyxml_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars)];

				yyxml_current_state = yyxml_get_previous_state(  );

				yyxml_cp = (yyxml_c_buf_p);
				yyxml_bp = (yyxmltext_ptr) + YY_MORE_ADJ;
				goto yyxml_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yyxmllex */

/* yyxml_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yyxml_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf;
	register char *source = (yyxmltext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yyxml_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yyxml_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yyxml_c_buf_p) - (yyxmltext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yyxml_c_buf_p) - (yyxmltext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yyxml_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars = (yyxml_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yyxml_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yyxml_c_buf_p_offset =
				(int) ((yyxml_c_buf_p) - b->yyxml_ch_buf);

			if ( b->yyxml_is_our_buffer )
				{
				int new_size = b->yyxml_buf_size * 2;

				if ( new_size <= 0 )
					b->yyxml_buf_size += b->yyxml_buf_size / 8;
				else
					b->yyxml_buf_size *= 2;

				b->yyxml_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyxmlrealloc((void *) b->yyxml_ch_buf,b->yyxml_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yyxml_ch_buf = 0;

			if ( ! b->yyxml_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yyxml_c_buf_p) = &b->yyxml_ch_buf[yyxml_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yyxml_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[number_to_move]),
			(yyxml_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars = (yyxml_n_chars);
		}

	if ( (yyxml_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyxmlrestart(yyxmlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yyxml_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyxml_size_t) ((yyxml_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yyxml_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yyxml_size_t new_size = (yyxml_n_chars) + number_to_move + ((yyxml_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf = (char *) yyxmlrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yyxml_get_next_buffer()" );
	}

	(yyxml_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yyxmltext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[0];

	return ret_val;
}

/* yyxml_get_previous_state - get the state just before the EOB char was reached */

    static yyxml_state_type yyxml_get_previous_state (void)
{
	register yyxml_state_type yyxml_current_state;
	register char *yyxml_cp;
    
	yyxml_current_state = (yyxml_start);

	for ( yyxml_cp = (yyxmltext_ptr) + YY_MORE_ADJ; yyxml_cp < (yyxml_c_buf_p); ++yyxml_cp )
		{
		register YY_CHAR yyxml_c = (*yyxml_cp ? yyxml_ec[YY_SC_TO_UI(*yyxml_cp)] : 1);
		if ( yyxml_accept[yyxml_current_state] )
			{
			(yyxml_last_accepting_state) = yyxml_current_state;
			(yyxml_last_accepting_cpos) = yyxml_cp;
			}
		while ( yyxml_chk[yyxml_base[yyxml_current_state] + yyxml_c] != yyxml_current_state )
			{
			yyxml_current_state = (int) yyxml_def[yyxml_current_state];
			if ( yyxml_current_state >= 21 )
				yyxml_c = yyxml_meta[(unsigned int) yyxml_c];
			}
		yyxml_current_state = yyxml_nxt[yyxml_base[yyxml_current_state] + (unsigned int) yyxml_c];
		}

	return yyxml_current_state;
}

/* yyxml_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yyxml_try_NUL_trans( current_state );
 */
    static yyxml_state_type yyxml_try_NUL_trans  (yyxml_state_type yyxml_current_state )
{
	register int yyxml_is_jam;
    	register char *yyxml_cp = (yyxml_c_buf_p);

	register YY_CHAR yyxml_c = 1;
	if ( yyxml_accept[yyxml_current_state] )
		{
		(yyxml_last_accepting_state) = yyxml_current_state;
		(yyxml_last_accepting_cpos) = yyxml_cp;
		}
	while ( yyxml_chk[yyxml_base[yyxml_current_state] + yyxml_c] != yyxml_current_state )
		{
		yyxml_current_state = (int) yyxml_def[yyxml_current_state];
		if ( yyxml_current_state >= 21 )
			yyxml_c = yyxml_meta[(unsigned int) yyxml_c];
		}
	yyxml_current_state = yyxml_nxt[yyxml_base[yyxml_current_state] + (unsigned int) yyxml_c];
	yyxml_is_jam = (yyxml_current_state == 20);

	return yyxml_is_jam ? 0 : yyxml_current_state;
}

    static void yyxmlunput (int c, register char * yyxml_bp )
{
	register char *yyxml_cp;
    
    yyxml_cp = (yyxml_c_buf_p);

	/* undo effects of setting up yyxmltext */
	*yyxml_cp = (yyxml_hold_char);

	if ( yyxml_cp < YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yyxml_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yyxml_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf )
			*--dest = *--source;

		yyxml_cp += (int) (dest - source);
		yyxml_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars =
			(yyxml_n_chars) = YY_CURRENT_BUFFER_LVALUE->yyxml_buf_size;

		if ( yyxml_cp < YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yyxml_cp = (char) c;

	(yyxmltext_ptr) = yyxml_bp;
	(yyxml_hold_char) = *yyxml_cp;
	(yyxml_c_buf_p) = yyxml_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyxmlinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yyxml_c_buf_p) = (yyxml_hold_char);

	if ( *(yyxml_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yyxml_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yyxml_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yyxml_ch_buf[(yyxml_n_chars)] )
			/* This was really a NUL. */
			*(yyxml_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yyxml_c_buf_p) - (yyxmltext_ptr);
			++(yyxml_c_buf_p);

			switch ( yyxml_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yyxml_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyxmlrestart(yyxmlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yyxmlwrap( ) )
						return EOF;

					if ( ! (yyxml_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyxmlinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yyxml_c_buf_p) = (yyxmltext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yyxml_c_buf_p);	/* cast for 8-bit char's */
	*(yyxml_c_buf_p) = '\0';	/* preserve yyxmltext */
	(yyxml_hold_char) = *++(yyxml_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyxmlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyxmlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yyxml_create_buffer(yyxmlin,YY_BUF_SIZE );
	}

	yyxml_init_buffer(YY_CURRENT_BUFFER,input_file );
	yyxml_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyxml_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yyxmlpop_buffer_state();
	 *		yyxmlpush_buffer_state(new_buffer);
     */
	yyxmlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yyxml_c_buf_p) = (yyxml_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yyxml_buf_pos = (yyxml_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars = (yyxml_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yyxml_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yyxmlwrap()) processing, but the only time this flag
	 * is looked at is after yyxmlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yyxml_did_buffer_switch_on_eof) = 1;
}

static void yyxml_load_buffer_state  (void)
{
    	(yyxml_n_chars) = YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars;
	(yyxmltext_ptr) = (yyxml_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yyxml_buf_pos;
	yyxmlin = YY_CURRENT_BUFFER_LVALUE->yyxml_input_file;
	(yyxml_hold_char) = *(yyxml_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyxml_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyxmlalloc(sizeof( struct yyxml_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yyxml_create_buffer()" );

	b->yyxml_buf_size = size;

	/* yyxml_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yyxml_ch_buf = (char *) yyxmlalloc(b->yyxml_buf_size + 2  );
	if ( ! b->yyxml_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yyxml_create_buffer()" );

	b->yyxml_is_our_buffer = 1;

	yyxml_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yyxml_create_buffer()
 * 
 */
    void yyxml_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yyxml_is_our_buffer )
		yyxmlfree((void *) b->yyxml_ch_buf  );

	yyxmlfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyxmlrestart() or at EOF.
 */
    static void yyxml_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yyxml_flush_buffer(b );

	b->yyxml_input_file = file;
	b->yyxml_fill_buffer = 1;

    /* If b is the current buffer, then yyxml_init_buffer was _probably_
     * called from yyxmlrestart() or through yyxml_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yyxml_bs_lineno = 1;
        b->yyxml_bs_column = 0;
    }

        b->yyxml_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyxml_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yyxml_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yyxml_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yyxml_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yyxml_buf_pos = &b->yyxml_ch_buf[0];

	b->yyxml_at_bol = 1;
	b->yyxml_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yyxml_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyxmlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyxmlensure_buffer_stack();

	/* This block is copied from yyxml_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yyxml_c_buf_p) = (yyxml_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yyxml_buf_pos = (yyxml_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yyxml_n_chars = (yyxml_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yyxml_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yyxml_switch_to_buffer. */
	yyxml_load_buffer_state( );
	(yyxml_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyxmlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yyxml_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yyxml_buffer_stack_top) > 0)
		--(yyxml_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yyxml_load_buffer_state( );
		(yyxml_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyxmlensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yyxml_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yyxml_buffer_stack) = (struct yyxml_buffer_state**)yyxmlalloc
								(num_to_alloc * sizeof(struct yyxml_buffer_state*)
								);
		if ( ! (yyxml_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyxmlensure_buffer_stack()" );
								  
		memset((yyxml_buffer_stack), 0, num_to_alloc * sizeof(struct yyxml_buffer_state*));
				
		(yyxml_buffer_stack_max) = num_to_alloc;
		(yyxml_buffer_stack_top) = 0;
		return;
	}

	if ((yyxml_buffer_stack_top) >= ((yyxml_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yyxml_buffer_stack_max) + grow_size;
		(yyxml_buffer_stack) = (struct yyxml_buffer_state**)yyxmlrealloc
								((yyxml_buffer_stack),
								num_to_alloc * sizeof(struct yyxml_buffer_state*)
								);
		if ( ! (yyxml_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyxmlensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yyxml_buffer_stack) + (yyxml_buffer_stack_max), 0, grow_size * sizeof(struct yyxml_buffer_state*));
		(yyxml_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yyxml_scan_buffer  (char * base, yyxml_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyxmlalloc(sizeof( struct yyxml_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yyxml_scan_buffer()" );

	b->yyxml_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yyxml_buf_pos = b->yyxml_ch_buf = base;
	b->yyxml_is_our_buffer = 0;
	b->yyxml_input_file = 0;
	b->yyxml_n_chars = b->yyxml_buf_size;
	b->yyxml_is_interactive = 0;
	b->yyxml_at_bol = 1;
	b->yyxml_fill_buffer = 0;
	b->yyxml_buffer_status = YY_BUFFER_NEW;

	yyxml_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yyxmllex() will
 * scan from a @e copy of @a str.
 * @param yyxmlstr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yyxml_scan_bytes() instead.
 */
YY_BUFFER_STATE yyxml_scan_string (yyxmlconst char * yyxmlstr )
{
    
	return yyxml_scan_bytes(yyxmlstr,strlen(yyxmlstr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yyxmllex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yyxml_scan_bytes  (yyxmlconst char * yyxmlbytes, int  _yyxmlbytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yyxml_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yyxmlbytes_len + 2;
	buf = (char *) yyxmlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yyxml_scan_bytes()" );

	for ( i = 0; i < _yyxmlbytes_len; ++i )
		buf[i] = yyxmlbytes[i];

	buf[_yyxmlbytes_len] = buf[_yyxmlbytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yyxml_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yyxml_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yyxml_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yyxml_fatal_error (yyxmlconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyxmlless() so it works in section 3 code. */

#undef yyxmlless
#define yyxmlless(n) \
	do \
		{ \
		/* Undo effects of setting up yyxmltext. */ \
        int yyxmlless_macro_arg = (n); \
        YY_LESS_LINENO(yyxmlless_macro_arg);\
		yyxmltext[yyxmlleng] = (yyxml_hold_char); \
		(yyxml_c_buf_p) = yyxmltext + yyxmlless_macro_arg; \
		(yyxml_hold_char) = *(yyxml_c_buf_p); \
		*(yyxml_c_buf_p) = '\0'; \
		yyxmlleng = yyxmlless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyxmlget_lineno  (void)
{
        
    return yyxmllineno;
}

/** Get the input stream.
 * 
 */
FILE *yyxmlget_in  (void)
{
        return yyxmlin;
}

/** Get the output stream.
 * 
 */
FILE *yyxmlget_out  (void)
{
        return yyxmlout;
}

/** Get the length of the current token.
 * 
 */
int yyxmlget_leng  (void)
{
        return yyxmlleng;
}

/** Get the current token.
 * 
 */

char *yyxmlget_text  (void)
{
        return yyxmltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyxmlset_lineno (int  line_number )
{
    
    yyxmllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yyxml_switch_to_buffer
 */
void yyxmlset_in (FILE *  in_str )
{
        yyxmlin = in_str ;
}

void yyxmlset_out (FILE *  out_str )
{
        yyxmlout = out_str ;
}

int yyxmlget_debug  (void)
{
        return yyxml_flex_debug;
}

void yyxmlset_debug (int  bdebug )
{
        yyxml_flex_debug = bdebug ;
}

static int yyxml_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yyxmllex_destroy(), so don't allocate here.
     */

    (yyxml_buffer_stack) = 0;
    (yyxml_buffer_stack_top) = 0;
    (yyxml_buffer_stack_max) = 0;
    (yyxml_c_buf_p) = (char *) 0;
    (yyxml_init) = 0;
    (yyxml_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyxmlin = stdin;
    yyxmlout = stdout;
#else
    yyxmlin = (FILE *) 0;
    yyxmlout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yyxmllex_init()
     */
    return 0;
}

/* yyxmllex_destroy is for both reentrant and non-reentrant scanners. */
int yyxmllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yyxml_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yyxmlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyxmlfree((yyxml_buffer_stack) );
	(yyxml_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yyxmllex() is called, initialization will occur. */
    yyxml_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yyxmltext_ptr
static void yyxml_flex_strncpy (char* s1, yyxmlconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yyxml_flex_strlen (yyxmlconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyxmlalloc (yyxml_size_t  size )
{
	return (void *) malloc( size );
}

void *yyxmlrealloc  (void * ptr, yyxml_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyxmlfree (void * ptr )
{
	free( (char *) ptr );	/* see yyxmlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yyxmltables"

#line 101 "sax.l"



int yyxmlwrap(void) { return 1; }

void yyxmlerror(const char *text) {
  std::ostringstream o;
  o << "XML Parsing Error: " << text << " (\"" << yyxmltext << "\")." << endl;
  Error::getInstance()->throwError(o.str().c_str());
}

